version: "3.7"
services:
  noise-api:
    build: .
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: uvicorn noise_api.api.main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
    depends_on:
      - celery-worker
      - redis
  
  redis:
    container_name: redis-noise-api
    image: redis:6.2-alpine
    expose: 
      - ${REDIS_PORT}
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  celery-worker:
    container_name: celery-worker-noise-api
    build: .
    restart: "always"
    command: celery -A noise_api.tasks worker --loglevel=info
    networks: *network_mode
    env_file:
      - .env
    volumes:
      - ./:/app
  
  # flower-noise-api:
  #   container_name: flower-noise-api
  #   build: .
  #   command: celery -A noise_api.tasks flower --port=5555
  #   networks: *network_mode
  #   ports:
  #     - '5556:5555'
  #   env_file:
  #     - .env

networks:
  bridgenet:
    driver: bridge