version: "3.7"
services:
  noise-api:
    build: .
    env_file: .env
    ports:
      - '8000:80'
    command: uvicorn noise_api.api.main:app --host 0.0.0.0 --port 80 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
  
  redis-noise-api:
    container_name: redis-noise-api
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  celery-worker-noise-api:
    container_name: celery-worker-noise-api
    build: .
    restart: "always"
    command: celery -A noise_api.tasks worker --loglevel=info
    networks: *network_mode
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - noise-api
      - redis-noise-api
  
  flower-noise-api:
    container_name: flower-noise-api
    build: .
    command: celery -A noise_api.tasks flower --port=5555
    networks: *network_mode
    ports:
      - '5556:5555'
    env_file:
      - .env
    depends_on:
      - noise-api
      - redis-noise-api
      - celery-worker-noise-api

networks:
  bridgenet:
    driver: bridge